name: visionzerobotmonthly

on:
  schedule:
    - cron: '0 10 12 * *'
  workflow_dispatch:


jobs:
  visionzerobot-post:
    runs-on: macOS-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_CONSUMER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_CONSUMER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install required packages
        run: Rscript -e 'install.packages(c("tidyverse", "rtweet", "sf", "lubridate", "jsonlite", "toOrdinal", "gghighlight"), dependencies = TRUE)'
      - name: Create and post monthly history tweet
        run: Rscript monthly_summary_history.R
