name: visionzerobotmonthly

on:
  schedule:
    - cron: '0 10 12 * *'
  workflow_dispatch:


jobs:
  visionzerobot-post:
    runs-on: macOS-latest
    env:
      RTOOT_DEFAULT_TOKEN: ${{ secrets.RTOOT_DEFAULT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install required packages
        run: Rscript -e 'install.packages(c("tidyverse", "rtoot", "sf", "lubridate", "jsonlite", "toOrdinal", "gghighlight"), dependencies = TRUE)'
      - name: Create and post monthly history toot
        run: Rscript monthly_summary_history.R
